# Configuración de Google Drive para Dashboard Fiebre Amarilla
# Copia este archivo como .streamlit/secrets.toml y configura tus IDs

[google_drive]
# IDs de archivos en Google Drive (obtener desde URL)
# Formato: https://drive.google.com/file/d/ID_DEL_ARCHIVO/view

# 🔴 CRÍTICOS (obligatorios):
vacunacion_csv_id = "TU_ID_DE_VACUNACION_CSV"
barridos_xlsx_id = "TU_ID_DE_BARRIDOS_XLSX"

# 🟡 OPCIONALES (mejoran funcionalidad):
poblacion_xlsx_id = "TU_ID_DE_POBLACION_XLSX"  # Opcional en v2.5
logo_id = "TU_ID_DE_LOGO_PNG"  # Opcional

# Nota v2.5: 
# - poblacion_xlsx_id es opcional, dashboard funciona sin él
# - No se requieren configuraciones de EAPB (eliminadas)
